advcbv/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^app/', include('app.urls')),
]

app/urls.py
from django.conf.urls import url
from app import views

app_name = 'app'


urlpatterns = [
    url(r'^$',views.SchoolListView.as_view(), name="list"),
    url(r'^(?P<pk>\d+)/$',views.SchoolDetailView.as_view(), name="detail"),   #necessarily the guy should be pk
    url(r'^create/$', views.SchoolCreateView.as_view(), name="create"),
    url(r'^update/(?P<pk>\d+)/$', views.SchoolUpdateView.as_view(), name="update"),
    url(r'^delete/(?P<pk>\d+)/$', views.SchoolDeleteView.as_view(), name="delete"),
]

app/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("app:detail", kwargs={'pk':self.pk})  #kwargs gives pk because the url is hooked up to SchoolDetailView and
                        #that needs a pk (see the url it takes pk )

class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name="students")


    def __str__(self):
        return self.name

app/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.http import HttpResponse
from . import models
from django.core.urlresolvers import reverse_lazy



class IndexView(TemplateView):
    template_name = 'index.html'


class SchoolListView(ListView):  #TO LIST ALL OBJECTS OF A MODEL
    model = models.School
    #it takes the model then lower cases everything and adds _list in the end so we have school_list
    #if you wanna bypass this then use the following cmd
    context_object_name = "schools"

    #also the template it wants is school_list.html so this file name is also compulsory

class SchoolDetailView(DetailView): #TO SHOW ALL THE DETAILS OF AN OBJECT OF A MODEL
    model = models.School
    context_object_name = "school_detail" #default is just school it just lowercases everything thats it!
    template_name = "app/school_detail.html"


#IT AUTOMATICALLY PASSES THE FORM NAME!!  AND OBJECT NAME IS : form
class SchoolCreateView(CreateView):  #alt to the view which calls forms which take data for a model
    model = models.School
    fields = "__all__"  #or ["name" ,"principal","location"]
    template_name = "app/create_school.html"  #default is school_form.html  is lowercase the model and add _form
    #it looks for the file in the app's folder named templates and under that  put ur shit inside that



#IT AUTOMATICALLY PASSES THE FORM NAME!!  AND OBJECT NAME IS : form
class SchoolUpdateView(UpdateView):
    model = models.School
    fields = ["name","principal"]
    template_name = "app/create_school.html"


class SchoolDeleteView(DeleteView):
    model = models.School
    success_url =  reverse_lazy("app:list")                        #Don't wanna hardcode urls
    template_name = "app/delete_school.html"
    context_object_name = "school"  #btw this is the default name <3

app/templates/app/app_base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <title>{% block title %}BASE{% endblock %}</title>
</head>

<body>

  <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top" style="margin-bottom:100px;">
    <div class="container">
      <a href="#" class="navbar-brand">Django</a>
      <button class="navbar-toggler" data-toggle="collapse" data-target="#myNav"><span class="navbar-toggler-icon"></span></button>
      <div id="myNav" class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a href="{% url 'admin:index' %}" class="nav-link">Admin</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'app:list' %}" class="nav-link">School List</a>
          </li>
        </ul>
    </div>
    </div>
  </nav>
  <div class="container" style="margin-top:100px;">
    {% block body %}

    {% endblock %}
  </div>


  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

app/templates/app/create_school.html
{% extends 'app/app_base.html'%}
{% block title %}Create New School{% endblock %}

{% block body %}

  <h1>
    {% if form.instance.pk %}
      Update School
    {% else %}
      Create School
    {% endif %}
  </h1>

  <form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>







{% endblock %}

app/templates/app/delete_school.html
{% extends "app/app_base.html" %}

{%block title%}Confirm Deletion{% endblock %}


{%block body%}
<h1>Confirm deleting {{school.name}}?</h1>

<form method="post">{% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Delete">
  <a href="{% url 'app:detail' pk=school.pk%}" class="btn btn-info">Cancel</a>
</form>
{%endblock%}

app/templates/app/school_detail.html
{% extends 'app/app_base.html' %}

{% block title %}School Details{% endblock %}


{% block body %}

  <div class="jumbotron">
    <h1>School's Details:</h1>
    <p>Name: {{ school_detail.name }}</p>
    <p>Principal: {{ school_detail.principal }}</p>
    <p>Location: {{ school_detail.location }}</p>

    <h3>Student Names:</h3>
    {% for student in school_detail.students.all %}
      <p>{{student.name}} who is {{student.age}} years old.</p>
    {% endfor %}
  </div>

  <div class="container">
    <p><a class="btn btn-warning" href="{% url 'app:update' pk=school_detail.pk %}">Update</a>
        <a class="btn btn-danger" href="{% url 'app:delete' pk=school_detail.pk %}">Delete</a>
    </p>
  </div>



{% endblock %}

app/templates/app/school_list.html
{% extends "app/app_base.html" %}  <!-- This is from templates with the app directory -->

{% block title %}School List{% endblock %}

{% block body %}

  <div class="jumbotron">
    <h1 class="display-2">Welcome to a list of all Schools!</h1>
    <ol>
      {% for school in schools %}
        <li><h3><a href="{{school.id}}">{{school.name}}</a></h3></li>
      {% endfor %}
    </ol>
  </div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <title>{% block title %}BASE{% endblock %}</title>
</head>

<body>

  <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top" style="margin-bottom:100px;">
    <div class="container">
      <a href="#" class="navbar-brand">Django</a>
      <button class="navbar-toggler" data-toggle="collapse" data-target="#myNav"><span class="navbar-toggler-icon"></span></button>
      <div id="myNav" class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a href="{% url 'admin:index' %}" class="nav-link">Admin</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'app:list' %}" class="nav-link">School List</a>
          </li>
        </ul>
    </div>
    </div>
  </nav>
  <div class="container" style="margin-top:100px;">
    {% block body %}

    {% endblock %}
  </div>


  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% block title %}INDEX{% endblock %}

{% block body %}
  <div class="jumbotron">
    <h1>Welcome to Home Page!!</h1>
  </div>
{% endblock %}